### PR TITLE
Added Jupyter for analysis + dependencies and small configuration change.

### PR DESCRIPTION
**Pull request by giladbau**
Added Jupyter for analysis, removed specific user configuration, updated .gitignore and requirements.txt

### CODE REVIEW

**Review by erasta — APPROVED** [review]

**Comment by erasta** [comment]
I wonder what your notebook does.
Thank you!

**Comment by giladbau** [comment]
It doesn't do a lot yet. Took me a while to get into the parsing

**Comment by erasta** [comment]
you could have used my parsing.... but maybe that would have been as problematic as pandas.

**Comment by giladbau** [comment]
I used your parsing :D

**Pull request merged**
